# Generated by Django 6.1 on 2026-08-12 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('bg_color', models.CharField(max_length=50)),
                ('border_color', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=10)),
                ('level', models.IntegerField(default=1)),
                ('total_levels', models.IntegerField(default=3)),
                ('order', models.IntegerField(default=0)),
                ('lessons', models.JSONField(blank=True, default=list)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.unit')),
            ],
            options={
                'ordering': ['unit__number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('hearts', models.IntegerField(default=5)),
                ('max_hearts', models.IntegerField(default=5)),
                ('gems', models.IntegerField(default=500)),
                ('daily_xp', models.IntegerField(default=0)),
                ('daily_goal', models.IntegerField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('current', 'Current'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
