# Generated by Django 6.1 on 2026-08-13 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_heart_refill',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
